/**
 * Bilingual dictionary (ja / en) for the whole site.
 * JA = source copy; EN = native professional translation.
 * Language-neutral data (repo names/urls/topics/dates, hrefs, numbers) lives in content.ts / works.ts.
 */

export const dict = {
  ja: {
    nav: { services: 'サービス', works: '活動', about: 'プロフィール', contact: 'お問い合わせ' },
    hero: {
      eyebrow: 'Fumito Ideguchi — Product Manager',
      line1: '企画から運用、',
      line2pre: '',
      gradient: 'AI',
      line2post: '活用・自動化まで。',
      sub: '受託でのプロダクト開発のディレクションから、業務のAI活用・自動化（DX）まで担当します。医療領域にも対応します。',
      indexHeading: '主な制作',
      roleIndex: { '01': '開発ディレクション', '02': 'AI・業務自動化（DX）', '03': 'プロダクトマネジメント' },
      ctaContact: 'お問い合わせ',
      ctaServices: 'サービスを見る',
      viewActivity: '活動を見る',
      careerHeading: '経歴',
      viewProfile: 'プロフィールを見る',
    },
    services: {
      eyebrow: 'SERVICES',
      heading: '事業内容',
      intro: 'プロダクトマネジメントを軸に、企画から運用・AI活用・業務自動化（DX）まで。医療領域にも対応します。',
      audienceLabel: '対象',
      areasLabel: '領域',
      items: [
        {
          title: '開発ディレクション',
          short: 'プロダクトの現場で連続した意思決定を担い、要件定義から開発推進・運用まで。',
          detail: 'プロダクトの現場における連続した意思決定を担います。事業の目的から逆算し、要件定義・優先度設計・開発推進・効果検証・運用までをディレクション。エンジニアと並走し、開発組織の仕組みと空気感を整えながら形にします。',
          audience: 'プロダクトの推進役・開発ディレクター／PdMを必要とする事業者',
          areas: ['要件定義', '優先度設計', '開発推進', '効果検証', '運用'],
        },
        {
          title: 'AI活用・業務自動化',
          short: '抽象的な要件から具体化、自動化まで、ざっくり請け負います。',
          detail: '「ざっくりこうしたい」レベルのご相談から丸ごとお任せでOK。抽象的な要件を具体化し、AI活用による業務自動化・DXの導入まで一気通貫で請け負い、現場で回る形に落とします。',
          audience: '業務の自動化・DX・AI活用を進めたい中小企業・チーム',
          areas: ['AI活用', '業務自動化', 'DX推進', 'データ活用'],
        },
        {
          title: '医療・医療DX相談',
          short: '医療分野の相談や、医療現場のデジタル化（医療DX）に対応します。',
          detail: '医療分野に関する相談や、医療現場のデジタル化・業務効率化・AI活用（医療DX）に対応します。',
          audience: '医療領域の知見・DXを必要とする医療機関・関連事業者',
          areas: ['医療ドメイン', '医療DX', '業務効率化'],
        },
      ],
    },
    capabilities: {
      eyebrow: '対応可能領域',
      items: ['プロダクト企画', '要件定義', '仮説検証', '効果検証', 'ロードマップ', 'データ活用', 'AI活用', '業務自動化', 'DX推進', '開発ディレクション'],
    },
    activity: {
      eyebrow: 'ACTIVITY',
      heading: '活動',
      intro: '自社開発・共同開発のプロダクトに加え、プロダクトマネジメントやAI活用のツールづくり・発信をオープンソースで続けています。',
      graphCaption: '直近3ヶ月のGitHubコントリビューション',
      commitsLabel: 'commits',
      contribEyebrow: 'CONTRIBUTIONS',
      legendLess: 'Less',
      legendMore: 'More',
      reposEyebrow: '制作・OSS',
      updatedLabel: '更新',
      viewAllGithub: 'GitHub で全て見る',
      collab: {
        eyebrow: 'COLLABORATION',
        title: 'WaWaTalk — 音声文字化デバイス',
        body: '株式会社メディモニーとの共同開発により、医師の言葉をリアルタイムで文字化するタブレット型デバイスを提供しています。',
        linkLabel: 'WaWaTalk を見る（株式会社メディモニー）',
        iframeTitle: 'WaWaTalk — 音声文字化デバイスのデモページ',
        caption: '※ 株式会社メディモニーが提供する WaWaTalk のサービスページです。',
      },
    },
    products: {
      eyebrow: 'プロダクト',
      privateBadge: '非公開',
      items: {
        kireinavi: { name: 'きれいナビ', label: '個人開発', description: '清掃業者向けの検索・予約サービス。決済をはじめ、清掃業者に必要な機能まで一通り揃えたプロダクト。企画から開発・運用まで一人で担当。' },
      },
    },
    repos: {
      my_pm_tools: { label: 'PMオペレーション', description: 'AI時代のPMオペレーター・スキル。GitHub Projects × Notion × Google Workspace を Claude Code から統合運用するMCPツール群。' },
      requirements_designer: { label: '要件定義', description: '対話型Q&Aで要件定義書（チャーター・FR/NFR・ユーザーストーリー・品質スコア）を生成する Claude Code スキル。' },
      pm_ad_analysis: { label: '広告運用', description: 'PM向けの広告運用エージェント。Google / Meta / ASA / TikTok / Amazon の5媒体に対応し、クリエイティブ生成・MMM・増分検証を支援。' },
      pm_data_analysis: { label: 'データ分析', description: 'CSV・JSON・画像を自律ルーティングで分析し、信頼度スコア付きのインサイトを生成する Claude Code スキル。' },
      bochi: { label: 'アイデア展開', description: 'アイデアの種を、ソクラテス式問答・SCAMPER・ReActリサーチで構造化された仮説に展開する Claude Code スキル。' },
      'speckit-bridge': { label: '要件→仕様', description: '要件定義（designs/）を spec-kit 形式（spec.md + constitution + conventions）に変換する Claude Code スキル。' },
      'figma-refine': { label: 'デザインレビュー', description: 'プロジェクト文脈を読み込み、3層スクリーンショット検証で Figma デザインを精緻化する Claude Code スキル。' },
      'medicavice-hp': { label: 'このサイト', description: 'このサイト自体のソースコード。Next.js 16 + React 19 + Tailwind v4 で構築。' },
    },
    about: {
      eyebrow: 'ABOUT',
      heading: 'プロフィール',
      itRole: '取締役 / プロダクトマネージャー',
      itNameEn: 'Fumito Ideguchi',
      itNameJa: '出口 史門',
      itBio: '事業会社・スタートアップでのプロダクトマネジメントを軸に、開発ディレクションやAI活用・業務自動化（DX）まで、企画から運用までを担います。',
      medRole: '代表取締役 / 医師',
      medName: '出口 誠',
      medBio: '長年の臨床経験を持つ医師。医療領域の知見が、医療・ヘルスケア分野の相談やDXの土台になっています。',
      companyEyebrow: '運営法人',
      careerNote: 'ほか 株式会社リスポ（FinTech）・LinQ・microverse・株式会社ミクシィ（みてね）・リクルート（新規事業）・ルームクリップ 等で PdM／PjM に従事。',
      company: [
        { label: '会社名', value: '株式会社メディカバイス' },
        { label: '設立', value: '令和6年10月' },
        { label: '資本金', value: '1,000,000円' },
        { label: '事業内容', value: '開発ディレクション・プロダクトマネジメント / AI活用・業務自動化 / 医療・医療DX相談' },
        { label: '役員', value: '代表取締役社長　出口誠\n取締役　出口史門' },
        { label: '所在地', value: '〒141-0031\n東京都品川区西五反田5丁目23番3号 5階5D室' },
        { label: '電話番号', value: '080-7532-4086' },
      ],
    },
    history: {
      it: [
        { period: '2024.6 – 現在', title: '株式会社メディカバイス｜取締役', sub: 'プロダクトマネジメント・開発ディレクション・AI/DX。業務委託やサービス開発。' },
        { period: '2025.6 – 2026.3', title: 'toCマッチングアプリ｜プロダクトマネージャー / 開発ディレクター', sub: '2025年3月リリースのサービスでPdMを担当。事業設計・バックログ運用・要件定義・効果検証。' },
        { period: '2023.2 – 2024.6', title: '株式会社Enginee｜CPO', sub: 'プロダクト責任者として EngineeBase を2023年8月にリリース。' },
        { period: '2021.9 – 2023.3', title: 'ディップ株式会社｜プロダクトマネージャー', sub: 'dip Robotics で社内向けCRMの施策ディレクション・要件定義・効果検証。' },
        { period: '2020.11 – 2023.2', title: 'Talknote株式会社｜プロジェクトマネージャー', sub: '組織活性化SaaS。データ基盤（DWH）構築・業務改善。' },
        { period: '2018.7 – 2020.3', title: 'GREE International｜プロダクトマネージャー', sub: 'オウンドメディア「aumo」で要件定義・効果検証など基礎を習得。' },
      ],
      med: [
        { period: '平成8年3月', title: '山口大学医学部 卒業' },
        { period: '平成15年', title: '京都大学大学院医学研究科 脳神経外科で再生医療研究' },
        { period: '平成16年9月', title: 'スタンフォード大学 2年3か月留学' },
        { period: '平成18年11月', title: '山口大学医学部附属病院 脳神経外科 助教' },
        { period: '令和2年6月', title: '五反田リハビリテーション病院勤務' },
        { period: '令和6年10月', title: '株式会社メディカバイス創業' },
      ],
      bartender: { period: '2025.2 – 2025.11', title: 'バーでバイト', sub: '武蔵小山のカラオケバーで接客。破格で1人のお客様も多いです。' },
    },
    contact: {
      eyebrow: 'CONTACT',
      heading: 'お問い合わせ',
      intro: '受託開発・技術コンサルティング・プロダクト開発・医療DXなど、医療・IT分野問わずお気軽にご相談ください。',
      reassuranceEyebrow: 'ご連絡について',
      reassurance: [
        { title: '返信目安：2営業日以内', body: '内容を確認のうえ、折り返しご連絡します。' },
        { title: 'オンライン対応', body: '打ち合わせはリモートでも対応可能です。' },
        { title: '守秘', body: 'いただいた情報を外部に開示することはありません。' },
      ],
      form: {
        required: '（必須）',
        optional: '（任意）',
        companyLabel: '会社名',
        companyPlaceholder: '株式会社〇〇',
        inquiryTypeLabel: 'お問い合わせ種別',
        inquiryTypePlaceholder: '選択してください',
        inquiryTypes: ['開発ディレクション', 'AI活用・業務自動化', '医療・医療DX相談', 'その他'],
        emailLabel: 'メールアドレス',
        emailPlaceholder: 'example@company.com',
        messageLabel: 'お問い合わせ内容',
        messagePlaceholder: 'ご相談内容をご記入ください',
        messageCounterSuffix: '/ 10,000',
        submit: '送信する',
        submitting: '送信中…',
        toastSuccess: 'お問い合わせを受け付けました。担当者よりご連絡いたします。',
        toastValidationError: '入力内容をご確認ください。',
        toastConfigError: '送信設定が不完全です。管理者にご連絡ください。',
        toastSendError: '送信中にエラーが発生しました。時間をおいて再度お試しください。',
      },
    },
    footer: {
      companyName: '株式会社メディカバイス',
      menuLabel: 'メニュー',
      locationLabel: '所在地・連携',
      address: '〒141-0031\n東京都品川区西五反田5-23-3',
      partner: '株式会社メディモニー',
      copyright: '© 株式会社メディカバイス All rights reserved.',
      privacyLink: '個人情報保護方針',
      homeAria: '株式会社メディカバイス — トップページへ',
      navAria: 'フッターナビゲーション',
    },
    ui: {
      logoText: 'メディカバイス',
      logoHomeAria: '株式会社メディカバイス — トップページへ',
      globalNavAria: 'グローバルナビゲーション',
      mobileNavAria: 'モバイルナビゲーション',
      openMenu: 'メニューを開く',
      closeMenu: 'メニューを閉じる',
      closeToast: '閉じる',
      skipToContent: 'メインコンテンツへスキップ',
      langToggleAria: 'Switch to English',
      langToggleLabel: 'EN',
    },
    validation: {
      companyRequired: '会社名を入力してください。',
      companyTooLong: '会社名は100文字以内で入力してください。',
      emailRequired: 'メールアドレスを入力してください。',
      emailInvalid: '正しいメールアドレス形式で入力してください。',
      messageRequired: 'お問い合わせ内容を入力してください。',
      messageTooLong: 'お問い合わせ内容は10,000文字以内で入力してください。',
    },
    notFound: {
      code: '404',
      heading: 'ページが見つかりません',
      body: 'お探しのページは移動または削除された可能性があります。お手数ですが、以下のリンクからお進みください。',
      backHome: 'トップページへ戻る',
      contact: 'お問い合わせ',
    },
    privacy: {
      eyebrow: 'PRIVACY',
      heading: '個人情報保護方針',
      intro: '株式会社メディカバイス（以下「当社」といいます。）は、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築し、全従業員に個人情報保護の重要性の認識と取組みを徹底させることにより、個人情報の保護を推進いたします。',
      sections: [
        { id: 1, title: '法令等の遵守', body: '当社は、「個人情報の保護に関する法律」および関連する政令・ガイドライン等を遵守し、個人情報を適切に取り扱います。' },
        { id: 2, title: '個人情報の取得・利用・提供', body: '当社は、個人情報を適正な手段により取得し、事前に特定した利用目的（各種コンサルティング業務、オンライン診療、お問い合わせ対応等）の達成に必要な範囲内で利用いたします。ご本人の同意なく、利用目的を超えて利用することはありません。第三者への提供についても、法令に定める場合を除き、あらかじめご本人の同意を得ます。' },
        { id: 3, title: '要配慮個人情報の取扱い', body: '当社は、美容医療オンライン診療等の事業運営において、ご本人の病歴や健康状態等の要配慮個人情報を取得する場合、法令に定められた例外的な場合を除き、必ずあらかじめご本人の同意を得た上で取得いたします。' },
        { id: 4, title: '個人情報の安全管理', body: '当社は、個人情報の漏えい、滅失、き損、改ざん、不正アクセス等を防止するため、組織的・技術的・物理的・人的な安全管理措置を講じ、継続的な改善に努めます。' },
        { id: 5, title: '委託先の管理', body: '当社は、個人情報の取扱いの全部または一部を外部に委託する場合、適切な委託先を選定するとともに、契約により個人情報の安全管理に関する必要な事項を定め、適切な監督を行います。' },
        { id: 6, title: '外国にある第三者への提供について', body: '当社は、法令に定める場合を除き、外国にある第三者に対して個人情報を提供いたしません。なお、当社は業務上、クラウドサービス（Microsoft Azure、AWS等）を利用しており、これらのサーバーが外国に設置されている場合があります。当社は当該クラウドサービス事業者においてデータへのアクセスが行われないよう適切なアクセス制御を講じる等、法令に基づく安全管理措置を実施しています。' },
        { id: 7, title: '個人情報の開示・訂正・利用停止・削除等', body: 'ご本人は、当社に対して、ご自身の個人情報の開示・訂正・追加・削除・利用停止・消去等を求めることができます。当該請求が法令に基づき正当なものであると認められる場合、ご本人確認を実施した上で、速やかに対応いたします。' },
        { id: 8, title: '継続的改善', body: '当社は、情報技術の発展や社会的要請の変化等を踏まえ、個人情報保護方針および運用体制の見直しを継続的に行い、その改善に努めます。' },
      ],
      contactTitle: 'お問い合わせ窓口',
      contactIntro: '当社の個人情報の取扱いに関するご相談・苦情・開示請求等については、以下までご連絡ください。',
      contactCompany: '株式会社メディカバイス',
      contactAddress: '所在地：〒141-0031 東京都品川区西五反田5丁目23番3号 5階5D室',
      contactHours: '受付時間：平日 9:00〜17:00（土日祝日除く）',
      enacted: ['制定日：2026年3月23日', '株式会社メディカバイス', '代表取締役社長　出口 誠'],
    },
  },

  en: {
    nav: { services: 'Services', works: 'Activity', about: 'Profile', contact: 'Contact' },
    hero: {
      eyebrow: 'Fumito Ideguchi — Product Manager',
      line1: 'From strategy to delivery,',
      line2pre: '',
      gradient: 'AI',
      line2post: ' adoption and automation.',
      sub: 'I lead product development on a contract basis and drive AI adoption and business automation (DX) — including in healthcare.',
      indexHeading: 'Selected work',
      roleIndex: { '01': 'Development direction', '02': 'AI & business automation (DX)', '03': 'Product management' },
      ctaContact: 'Contact',
      ctaServices: 'View services',
      viewActivity: 'View activity',
      careerHeading: 'Career',
      viewProfile: 'View profile',
    },
    services: {
      eyebrow: 'SERVICES',
      heading: 'Services',
      intro: 'Product management at the core — from strategy through delivery, operations, AI adoption, and business automation (DX). Healthcare included.',
      audienceLabel: 'For',
      areasLabel: 'Areas',
      items: [
        {
          title: 'Development Direction',
          short: 'Owning the continuous decisions on the ground — from requirements to delivery and operations.',
          detail: 'I own the continuous, on-the-ground decisions a product demands. Working back from the business goal, I direct requirements, prioritization, delivery, impact measurement, and operations — shaping how the engineering org works and feels as we ship.',
          audience: 'Businesses that need a product lead, development director, or PdM to drive things forward.',
          areas: ['Requirements', 'Prioritization', 'Delivery', 'Impact measurement', 'Operations'],
        },
        {
          title: 'AI Adoption & Business Automation',
          short: 'From a rough idea to something concrete and automated — I take it end to end.',
          detail: 'Start from a rough "I just want something like this" and hand it over. I turn vague ideas into something concrete and deliver AI-powered automation (DX) end to end — built to work in the real workflow.',
          audience: 'Small and mid-sized companies and teams looking to automate, modernize (DX), and adopt AI.',
          areas: ['AI', 'Business automation', 'DX', 'Data'],
        },
        {
          title: 'Healthcare & Healthcare DX',
          short: 'Advising on healthcare and digitizing clinical operations (healthcare DX).',
          detail: 'I advise on healthcare and help digitize clinical operations — improving workflows and bringing AI to the point of care (healthcare DX).',
          audience: 'Healthcare providers and related businesses that need medical domain expertise and DX.',
          areas: ['Medical domain', 'Healthcare DX', 'Workflow efficiency'],
        },
      ],
    },
    capabilities: {
      eyebrow: 'What I can take on',
      items: ['Product strategy', 'Requirements', 'Hypothesis testing', 'Impact measurement', 'Roadmapping', 'Data', 'AI', 'Business automation', 'DX', 'Development direction'],
    },
    activity: {
      eyebrow: 'ACTIVITY',
      heading: 'Activity',
      intro: 'Alongside in-house and joint product builds, I keep shipping and sharing open-source tools for product management and practical AI.',
      graphCaption: 'GitHub contributions over the past 3 months',
      commitsLabel: 'commits',
      contribEyebrow: 'CONTRIBUTIONS',
      legendLess: 'Less',
      legendMore: 'More',
      reposEyebrow: 'Builds / OSS',
      updatedLabel: 'Updated',
      viewAllGithub: 'See everything on GitHub',
      collab: {
        eyebrow: 'COLLABORATION',
        title: 'WaWaTalk — speech-to-text device',
        body: "Co-developed with Medimony Inc.: a tablet device that transcribes a doctor's speech in real time.",
        linkLabel: 'View WaWaTalk (Medimony Inc.)',
        iframeTitle: 'WaWaTalk — speech-to-text device demo',
        caption: '* The WaWaTalk service page provided by Medimony Inc.',
      },
    },
    products: {
      eyebrow: 'Products',
      privateBadge: 'Private',
      items: {
        kireinavi: { name: 'KireiNavi', label: 'Solo build', description: 'A search & booking service for cleaning companies — payments included, with the full set of features a cleaning business needs. Designed, built, and run end to end, solo.' },
      },
    },
    repos: {
      my_pm_tools: { label: 'PM Operations', description: "An operator's toolkit for PMs in the AI era — a set of MCP tools that run GitHub Projects, Notion, and Google Workspace together from Claude Code." },
      requirements_designer: { label: 'Requirements', description: 'A Claude Code skill that generates requirements docs — charter, FR/NFR, user stories, and a quality score — through an interactive Q&A.' },
      pm_ad_analysis: { label: 'Ad Operations', description: 'An ad-operations agent for PMs. Covers five channels — Google, Meta, ASA, TikTok, and Amazon — with creative generation, MMM, and incrementality testing.' },
      pm_data_analysis: { label: 'Data Analysis', description: 'A Claude Code skill that analyzes CSV, JSON, and images via autonomous routing and surfaces insights with confidence scores.' },
      bochi: { label: 'Idea Development', description: 'A Claude Code skill that grows a seed of an idea into a structured hypothesis through Socratic questioning, SCAMPER, and ReAct-style research.' },
      'speckit-bridge': { label: 'Requirements to Spec', description: 'A Claude Code skill that converts requirements (designs/) into spec-kit format — spec.md plus constitution and conventions.' },
      'figma-refine': { label: 'Design Review', description: 'A Claude Code skill that reads the project context and refines Figma designs with three-layer screenshot verification.' },
      'medicavice-hp': { label: 'This site', description: 'The source code for this very site. Built with Next.js 16, React 19, and Tailwind v4.' },
    },
    about: {
      eyebrow: 'ABOUT',
      heading: 'Profile',
      itRole: 'Director / Product Manager',
      itNameEn: 'Fumito Ideguchi',
      itNameJa: '出口 史門',
      itBio: 'Grounded in product management at operating companies and startups, I cover everything from strategy to operations — including development direction and AI-driven business automation (DX).',
      medRole: 'CEO / Physician',
      medName: 'Makoto Ideguchi',
      medBio: 'A physician with years of clinical experience. That medical expertise is the foundation for our healthcare advisory work and DX.',
      companyEyebrow: 'The company',
      careerNote: 'Also engaged as PdM/PjM at Respo (FinTech), LinQ, microverse, MIXI (mitene), Recruit (new ventures), RoomClip, and others.',
      company: [
        { label: 'Company', value: 'Medicavice Inc.' },
        { label: 'Founded', value: 'October 2024' },
        { label: 'Capital', value: 'JPY 1,000,000' },
        { label: 'Business', value: 'Development direction & product management / AI adoption & business automation / healthcare & healthcare DX advisory' },
        { label: 'Officers', value: 'Makoto Ideguchi, President & CEO\nFumito Ideguchi, Director' },
        { label: 'Address', value: '5D, 5F, 5-23-3 Nishigotanda\nShinagawa-ku, Tokyo 141-0031, Japan' },
        { label: 'Phone', value: '+81 80-7532-4086' },
      ],
    },
    history: {
      it: [
        { period: 'Jun 2024 – Present', title: 'Medicavice Inc. | Director', sub: 'Product management, development direction, and AI/DX — across contract work and in-house product development.' },
        { period: 'Jun 2025 – Mar 2026', title: 'Consumer matching app | Product Manager / Development Director', sub: 'PdM for a service launched March 2025: business design, backlog operations, requirements, and impact measurement.' },
        { period: 'Feb 2023 – Jun 2024', title: 'Enginee Inc. | CPO', sub: 'As head of product, launched EngineeBase in August 2023.' },
        { period: 'Sep 2021 – Mar 2023', title: 'Dip Corporation | Product Manager', sub: 'At dip Robotics, led initiative direction, requirements, and impact measurement for an internal CRM.' },
        { period: 'Nov 2020 – Feb 2023', title: 'Talknote Inc. | Project Manager', sub: 'Team-engagement SaaS. Built the data warehouse (DWH) and drove operational improvements.' },
        { period: 'Jul 2018 – Mar 2020', title: 'GREE International | Product Manager', sub: 'Learned the fundamentals — requirements, impact measurement, and more — on the owned media platform aumo.' },
      ],
      med: [
        { period: 'March 1996', title: 'Graduated, Yamaguchi University School of Medicine' },
        { period: '2003', title: 'Regenerative medicine research, Dept. of Neurosurgery, Kyoto University Graduate School of Medicine' },
        { period: 'September 2004', title: 'Stanford University — 2 years and 3 months of study abroad' },
        { period: 'November 2006', title: 'Assistant Professor, Dept. of Neurosurgery, Yamaguchi University Hospital' },
        { period: 'June 2020', title: 'Gotanda Rehabilitation Hospital' },
        { period: 'October 2024', title: 'Founded Medicavice Inc.' },
      ],
      bartender: { period: 'Feb 2025 – Nov 2025', title: 'Bar staff', sub: 'Serving at a karaoke bar in Musashi-Koyama — plenty of solo regulars, at unbeatable prices.' },
    },
    contact: {
      eyebrow: 'CONTACT',
      heading: 'Get in touch',
      intro: "Contract development, technical consulting, product development, healthcare DX — whether it's healthcare or IT, feel free to reach out.",
      reassuranceEyebrow: 'What to expect',
      reassurance: [
        { title: 'Reply within 2 business days', body: "I'll review your message and get back to you." },
        { title: 'Remote-friendly', body: 'Meetings can be held remotely.' },
        { title: 'Confidential', body: 'Anything you share stays private.' },
      ],
      form: {
        required: '(required)',
        optional: '(optional)',
        companyLabel: 'Company name',
        companyPlaceholder: 'Acme Inc.',
        inquiryTypeLabel: 'Inquiry type',
        inquiryTypePlaceholder: 'Select an option',
        inquiryTypes: ['Development direction', 'AI adoption & business automation', 'Healthcare & healthcare DX advisory', 'Other'],
        emailLabel: 'Email address',
        emailPlaceholder: 'example@company.com',
        messageLabel: 'Message',
        messagePlaceholder: "Tell me what you'd like to discuss.",
        messageCounterSuffix: '/ 10,000',
        submit: 'Send',
        submitting: 'Sending…',
        toastSuccess: 'Thanks — your message has been received. I\'ll be in touch soon.',
        toastValidationError: 'Please double-check your entries.',
        toastConfigError: "The contact form isn't fully configured. Please notify the site administrator.",
        toastSendError: 'Something went wrong while sending. Please wait a moment and try again.',
      },
    },
    footer: {
      companyName: 'Medicavice Inc.',
      menuLabel: 'Menu',
      locationLabel: 'Location & Partner',
      address: '141-0031\n5-23-3 Nishigotanda, Shinagawa-ku, Tokyo',
      partner: 'Medimony Inc.',
      copyright: '© Medicavice Inc. All rights reserved.',
      privacyLink: 'Privacy Policy',
      homeAria: 'Medicavice Inc. — back to home',
      navAria: 'Footer navigation',
    },
    ui: {
      logoText: 'Medicavice',
      logoHomeAria: 'Medicavice Inc. — back to home',
      globalNavAria: 'Global navigation',
      mobileNavAria: 'Mobile navigation',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      closeToast: 'Close',
      skipToContent: 'Skip to main content',
      langToggleAria: '日本語に切り替え',
      langToggleLabel: '日本語',
    },
    validation: {
      companyRequired: 'Please enter your company name.',
      companyTooLong: 'Company name must be 100 characters or fewer.',
      emailRequired: 'Please enter your email address.',
      emailInvalid: 'Please enter a valid email address.',
      messageRequired: 'Please enter your message.',
      messageTooLong: 'Message must be 10,000 characters or fewer.',
    },
    notFound: {
      code: '404',
      heading: 'Page not found',
      body: "The page you're looking for may have moved or been removed. Please use one of the links below to continue.",
      backHome: 'Back to home',
      contact: 'Contact',
    },
    privacy: {
      eyebrow: 'PRIVACY',
      heading: 'Privacy Policy',
      intro: 'Medicavice Inc. (hereinafter, "the Company") has established the following Privacy Policy. By building a framework for the protection of personal information and ensuring that every employee understands its importance and acts accordingly, the Company promotes the protection of personal information.',
      sections: [
        { id: 1, title: 'Compliance with Laws and Regulations', body: 'The Company complies with the Act on the Protection of Personal Information and related cabinet orders and guidelines, and handles personal information appropriately.' },
        { id: 2, title: 'Acquisition, Use, and Provision of Personal Information', body: 'The Company acquires personal information by lawful and fair means and uses it only within the scope necessary to achieve the purposes of use specified in advance (such as various consulting services, online medical care, and responding to inquiries). The Company will not use personal information beyond those purposes without the consent of the individual. The Company will also obtain the individual\'s prior consent before providing personal information to any third party, except as permitted by law.' },
        { id: 3, title: 'Handling of Sensitive Personal Information', body: 'When acquiring sensitive personal information such as an individual\'s medical history or health condition in the course of operating services such as online cosmetic-medicine care, the Company will, except in the exceptional cases permitted by law, always obtain the individual\'s prior consent before doing so.' },
        { id: 4, title: 'Security Management of Personal Information', body: 'To prevent leakage, loss, damage, alteration, or unauthorized access to personal information, the Company implements organizational, technical, physical, and personnel security measures, and strives for their continuous improvement.' },
        { id: 5, title: 'Supervision of Contractors', body: 'When the Company outsources all or part of the handling of personal information, it selects appropriate contractors, sets out the necessary matters regarding the security of personal information by contract, and exercises appropriate supervision.' },
        { id: 6, title: 'Provision to Third Parties in Foreign Countries', body: 'Except as permitted by law, the Company does not provide personal information to third parties located in foreign countries. The Company uses cloud services (such as Microsoft Azure and AWS) in the course of its business, and the servers for these services may be located outside Japan. The Company implements security measures in accordance with the law — including appropriate access controls so that the relevant cloud-service providers do not access the data.' },
        { id: 7, title: 'Disclosure, Correction, Suspension of Use, and Deletion', body: 'Individuals may request the disclosure, correction, addition, deletion, suspension of use, or erasure of their own personal information. Where such a request is recognized as legitimate under the law, the Company will respond promptly after verifying the identity of the individual.' },
        { id: 8, title: 'Continuous Improvement', body: 'In light of advances in information technology and changes in societal expectations, the Company continuously reviews and improves this Privacy Policy and its operational framework.' },
      ],
      contactTitle: 'Contact Window',
      contactIntro: 'For consultations, complaints, or disclosure requests regarding the Company\'s handling of personal information, please contact us at the following.',
      contactCompany: 'Medicavice Inc.',
      contactAddress: 'Address: 5D, 5F, 5-23-3 Nishigotanda, Shinagawa-ku, Tokyo 141-0031, Japan',
      contactHours: 'Hours: Weekdays 9:00–17:00 (excluding weekends and holidays)',
      enacted: ['Enacted: March 23, 2026', 'Medicavice Inc.', 'Makoto Ideguchi, President & CEO'],
    },
  },
}

export type Locale = keyof typeof dict
export type Dict = (typeof dict)['ja']
